### ISSUE TITLE
Prepare package

### ISSUE THREAD

**Issue by j-rossi-nl** [j-rossi-nl/python-fitbit#1]
I will suggest we publish it under a new name, and that we change the repository to help us manage dependencies and code style. I have used poetry and nox in other packages (deployed cookiecutter + hyper-modern-python for project template)

* Get a new name for PyPi (suggested: **py-fitbit-api**)
  * put the 3 of us as owners / administrators
* Make it a poetry managed package (e.g. using cookiecutter + hyper-modern-python)
* Github pre-commit
  * style (black)
  * linting (flake8)
  * etc?
* Setup github actions / checks (for validating PRs)
  * mypy ?
  * safety ?
  * pytest ?
  * coverage with codecov
  * auto docs to readthedocs.io

@chemelli74 @Ziip-dev 

I have experience with that, so I can do this in a PR.
 Let's discuss a bit and reach consensus before jumping into action.

**Comment by chemelli74** [comment]
I agree on changing the name; I think we can drop the suffix "`api`" as it's a library so is implicit.

About pre-commit and actions I fully agree; I think that take inspiration from [aioshelly](https://github.com/home-assistant-libs/aioshelly) that has a complete approach also for publishing the package.

About poetry I don't have any experience, so cannot comment.

Finally I would love to have devcontainer support.

Simone

**Comment by Ziip-dev** [comment]
I fully agree on poetry and I have rather good experience with it so I can even help on that side.

Regarding Github pre-commit however, I have no experience with either one solution or the other so I am not opinionated on the subject (will be keen on learning a modern process anyway) :)

Same stance on Github actions, small working knowledge with pytest but nothing that can make me inflect tools decision, I have to learn anyway.

**Comment by j-rossi-nl** [comment]
I'm making progress.
I have it all in place with poetry and so on.

The fun part: I activated the pre-commit and flake8 gives me 360 issues :) 
I will pick and choose those who are relevant and deactivate the  nitpicking ones.

Here is an overview:

```
code                                                           
D415    First line should end with a period, question ...    86
D212    Multi-line docstring summary should start at t...    75
D102                   Missing docstring in public method    43
D205    1 blank line required between summary line and...    34
D200    One-line docstring should fit on one line with...    34
B950                   line too long (90 > 80 characters)    16
N818    exception name 'BadResponse' should be named w...     9
D417       Missing argument descriptions in the docstring     8
N806      variable 'ARGS' in function should be lowercase     8
D100                   Missing docstring in public module     5
D101                    Missing docstring in public class     5
D202      No blank lines allowed after function docstring     5
E713               test for membership should be 'not in'     4
F841    local variable 'retval' is assigned to but nev...     4
D103                 Missing docstring in public function     4
N802    function name '_COLLECTION_RESOURCE' should be...     2
D107                        Missing docstring in __init__     2
S105     Possible hardcoded password: 'fake_access_token'     2
B904    Within an `except` clause, raise exceptions wi...     2
E731         do not assign a lambda expression, use a def     2
F401                    '.api.Fitbit' imported but unused     2
RST202  Bullet list ends without a blank line; unexpec...     2
B006    Do not use mutable data structures for argumen...     1
N801    class name 'fake_response' should use CapWords...     1
D403    First word of the first line should be properl...     1
B903    Data class should either be immutable or use _...     1
D201     No blank lines allowed before function docstring     1
D104                  Missing docstring in public package     1
S107                      Possible hardcoded password: ''     1
```

D are documentation-related, S are security-related, B are formatting.
I'll start a PR so you can see progress and we can discuss.

**Comment by chemelli74** [comment]
For black we can use the settings from HomeAssistant that are really equilibrate

**Comment by chemelli74** [comment]
Please join [Discord](https://discord.com/invite/home-assistant) and then contact me: `chemelli74#2180`

I would like to create a group for easy discussions and sharing.

Simone

**Comment by Ziip-dev** [comment]
> Please join [Discord](https://discord.com/invite/home-assistant) and then contact me: `chemelli74#2180`

Done
